spring:
  main:
    banner-mode: log
  config:
    import: "configtree:db/"

  application:
    name: @project.artifactId@

  h2:
    console:
      enabled: on

  sql:
    init:
      mode: never

  liquibase:
    change-log: "classpath:/db/changelog/db.changelog-master.xml"
    test-rollback-on-update: on

  datasource:
    url: ${app.database}
    username: ${app.username:sa}
    password: ${app.password}
    driverClassName: org.h2.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none

  codec:
    log-request-details: on

server:
  port: 8080
  error:
    include-exception: on
    include-stacktrace: always

management:
  server:
    port: @management.port@
  endpoints:
    web:
      exposure:
        include: health, openapi, swaggerui # For yaml format access /actuator/openapi/springdocDefault/yaml

springdoc:
  use-management-port: on
  show-actuator: on
  api-docs:
    enabled: on
    path: /api-docs

apidoc:
  title: @project.name@
  description: @project.description@
  version: @project.version@

debug: off
trace: off
logging:
  file:
    path: /var/log/@build.name@
  level:
    root: error
    web: trace
    sql: trace
    org:
      springframework:
        jdbc:
          datasource: trace